apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rhods-notebooks
commonLabels:
  app: assign-class-label-webhook

resources:
  - issuer.yaml
  - certificate.yaml
  - deployment.yaml
  - service.yaml
  - webhook-config.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
